# Generated by Django 5.1.2 on 2024-10-09 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_dealer_distributor_remove_dealer_factory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.distributor'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.factory'),
        ),
        migrations.AlterField(
            model_name='ie',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.retailer'),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.dealer'),
        ),
    ]
