# Generated by Django 5.1.2 on 2024-10-09 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_dealer_supplier_alter_distributor_supplier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='level',
        ),
        migrations.RemoveField(
            model_name='distributor',
            name='level',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='level',
        ),
        migrations.RemoveField(
            model_name='ie',
            name='level',
        ),
        migrations.RemoveField(
            model_name='ie',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='retailer',
            name='level',
        ),
        migrations.RemoveField(
            model_name='retailer',
            name='supplier',
        ),
    ]
