# Generated by Django 5.1.2 on 2024-10-09 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_dealer_level_remove_distributor_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributor',
            name='address',
        ),
        migrations.AddField(
            model_name='distributor',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.address'),
        ),
    ]
