# Generated by Django 5.1.2 on 2024-10-09 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_distributor_address_distributor_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='address',
        ),
        migrations.AddField(
            model_name='distributor',
            name='address',
            field=models.ManyToManyField(blank=True, to='shop.address'),
        ),
        migrations.AddField(
            model_name='factory',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.address'),
        ),
    ]
