# Generated by Django 5.1.2 on 2024-10-09 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_distributor_address_remove_factory_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealer',
            old_name='supplier',
            new_name='distributor',
        ),
        migrations.RenameField(
            model_name='distributor',
            old_name='supplier',
            new_name='factory',
        ),
        migrations.RemoveField(
            model_name='ie',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='retailer',
            name='phone',
        ),
        migrations.AddField(
            model_name='dealer',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.factory'),
        ),
        migrations.AddField(
            model_name='ie',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.dealer'),
        ),
        migrations.AddField(
            model_name='ie',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.distributor'),
        ),
        migrations.AddField(
            model_name='ie',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.factory'),
        ),
        migrations.AddField(
            model_name='ie',
            name='retailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.retailer'),
        ),
        migrations.AddField(
            model_name='retailer',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.dealer'),
        ),
        migrations.AddField(
            model_name='retailer',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.distributor'),
        ),
        migrations.AddField(
            model_name='retailer',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.factory'),
        ),
    ]
