# Generated by Django 5.1.2 on 2024-10-09 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_rename_supplier_dealer_distributor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='distributor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='ie',
            name='address',
        ),
        migrations.RemoveField(
            model_name='retailer',
            name='address',
        ),
        migrations.AddField(
            model_name='dealer',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.address'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.address'),
        ),
        migrations.AddField(
            model_name='ie',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.address'),
        ),
        migrations.AddField(
            model_name='retailer',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.address'),
        ),
    ]
