# Generated by Django 5.1.2 on 2024-10-09 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_dealer_address_remove_distributor_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='shop.product'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='shop.product'),
        ),
        migrations.AddField(
            model_name='factory',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='shop.product'),
        ),
        migrations.AddField(
            model_name='ie',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='shop.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.factory'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='retailer',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='shop.product'),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
