# Generated by Django 5.1.2 on 2024-10-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_dealer_products_distributor_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='products',
            field=models.ManyToManyField(blank=True, to='shop.product'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='products',
            field=models.ManyToManyField(blank=True, to='shop.product'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='products',
            field=models.ManyToManyField(blank=True, to='shop.product'),
        ),
        migrations.AlterField(
            model_name='ie',
            name='products',
            field=models.ManyToManyField(blank=True, to='shop.product'),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='products',
            field=models.ManyToManyField(blank=True, to='shop.product'),
        ),
    ]
