# Generated by Django 5.1.2 on 2024-10-09 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_dealer_products_alter_distributor_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='products',
        ),
        migrations.RemoveField(
            model_name='distributor',
            name='products',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='products',
        ),
        migrations.RemoveField(
            model_name='ie',
            name='products',
        ),
        migrations.RemoveField(
            model_name='retailer',
            name='products',
        ),
    ]
