# Generated by Django 5.1.2 on 2024-10-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_product_dealer_product_distributor_product_ie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dealer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='distributor',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ie',
        ),
        migrations.RemoveField(
            model_name='product',
            name='retailer',
        ),
        migrations.AddField(
            model_name='product',
            name='dealer',
            field=models.ManyToManyField(blank=True, to='shop.dealer'),
        ),
        migrations.AddField(
            model_name='product',
            name='distributor',
            field=models.ManyToManyField(blank=True, to='shop.distributor'),
        ),
        migrations.AddField(
            model_name='product',
            name='ie',
            field=models.ManyToManyField(blank=True, to='shop.ie'),
        ),
        migrations.AddField(
            model_name='product',
            name='retailer',
            field=models.ManyToManyField(blank=True, to='shop.retailer'),
        ),
    ]
