# Generated by Django 5.1.2 on 2024-10-09 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_remove_product_dealer_remove_product_distributor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='dealer',
            new_name='dealers',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='distributor',
            new_name='distributors',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='ie',
            new_name='ies',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='retailer',
            new_name='retailers',
        ),
    ]
