# Generated by Django 5.1.2 on 2024-10-09 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_remove_employee_date_of_admission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factory',
            name='phone',
        ),
    ]
